### PR TITLE
Add code + 3D models to repo, and create documentation website

### PR DESCRIPTION
**Pull request by r-tae**
- Creates a (very basic for now) documentation website and moved the contents of the Word documents there. You can see my test version at https://r-tae.github.io/Farbung/, when the PR is merged it will build and create the same site at your own url: https://FilmNeverDie.github.io/Farbung/. If you want to use a custom URL (e.g. cp800.filmneverdie.com) in the future that's easy to set up, and of course it can be branded/themed etc.

- Added most of the sharepoint files to the repository. It's structured slightly differently to the sharepoint but its easy to change if something doesn't make sense.

- Applied the 3-clause BSD for source code.

### CODE REVIEW

**Review by cychu18 — APPROVED** [review]

**Review by cychu18 — APPROVED** [review]

**Review by cychu18 — APPROVED** [review]

**Review by cychu18 — CHANGES_REQUESTED** [review]
for future project section, refurbish / fixing roller transport /pull thru machine is not part of this github project please remove the item from the dot points

**Review by cychu18 — APPROVED** [review]

**Comment by cychu18** [comment]
> for future project section, refurbish / fixing roller transport /pull thru machine is not part of this github project please remove the item from the dot points

well, actually i can do that myself after the merge, i believe

**Comment by r-tae** [comment]
> well, actually i can do that myself after the merge, i believe

Oh thanks, I was just about to push the change anyway but that works too

**Comment by r-tae** [comment]
On the subject of this PR, you can see that the docs build failed (here https://github.com/FilmNeverDie/Farbung/actions)

You just need to add the FilmNeverDie account's GitHub token to the Actions secrets, for the website to be built and deployed to https://filmneverdie.github.io/Farbung/

I can find a guide for this if you have any trouble

**Comment by cychu18** [comment]
> On the subject of this PR, you can see that the docs build failed (here https://github.com/FilmNeverDie/Farbung/actions)
> 
> You just need to add the FilmNeverDie account's GitHub token to the Actions secrets, for the website to be built and deployed to https://filmneverdie.github.io/Farbung/
> 
> I can find a guide for this if you have any trouble

yes a guide would be good. also,  gary has the FND account. I will talk to him about it. I will try to see if my acc can do the same action.

**Pull request merged**
